#!/bin/bash
set -euxo pipefail

formulas=( \
  1password \
  Alfred \
  docker \
  iterm2 \
  google-chrome \
  slack \
  dropbox \
  java \
  visual-studio-code \
  vivaldi \
  bartender \
  google-backup-and-sync \
  bettertouchtool \
  boostnote \
  box-drive \
  box-edit \
  clipy \
  discord \
  drawio \
  dropbox \
  karabiner-elements \
  kindle \
  microsoft-edge \
  notion \
  sourcetree \
  textexpander \
  vlc \
  atok \
)

for formula in "${formulas[@]}"; do
  tools/brew-cask-install "$formula"
done
