#!/bin/bash
set -euxo pipefail

brew update

formulas=( \
cloudfoundry/tap/cf-cli \
ansible \
autoconf \
autojump \
automake \
awscli \
boost \
cmigemo \
ctags \
curl \
direnv \
libtool \
gdal \
gibo \
git \
go \
graphviz \
heroku/brew/heroku \
hub \
hugo  \
jq  \
lv \
mas \
p7zip \
peco \
plantuml \
redis \
rbenv \
rust \
nodenv \
tfenv \
the_platinum_searcher \
tig \
tmux \
tree \
vim \
wget \
zsh \
zsh-completions \
)

if ! command -v node >/dev/null 2>&1; then
  tools/brew-install "node"
fi

for formula in "${formulas[@]}"; do
  tools/brew-install "$formula"
done