#!/bin/bash
set -euxo pipefail

target=$XDG_DATA_HOME/src/github.com/xtatsux/dotfiles

tools/git-clone https://github.com/xtatsux/dotfiles "$target"

for f in  .zshrc .gitconfig .gitignore .vimrc .gvimrc .tmux.conf .tmux-powerlinerc; do
  tools/make-symlink "$target/$f" ~/"$f"
done
for f in .zshrc .zpreztorc .zlogin .zlogout .zshenv .zprofile; do
  tools/make-symlink "$target/$f" "$ZDOTDIR/$f"
done

mkdir -p "$XDG_CACHE_HOME"/vim/{swap,backup,undo}
mkdir -p "$XDG_DATA_HOME"/vim

# Create fish config directory and symlinks
mkdir -p ~/fish
for f in config.fish fishfile; do
  tools/make-symlink "$target/fish/$f" ~/fish/"$f"
done
