#!/bin/zsh
set -euxo pipefail

# install prezto
[ ! -d ~/.zprezto ] && git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
setopt EXTENDED_GLOB

# install tmux-powerline
[ ! -d ~/tool/tmux-powerline ] && git clone git://github.com/erikw/tmux-powerline.git ~/tool/tmux-powerline

# install go app
go get -u github.com/motemen/ghq
go get -u github.com/typester/gh-open

# install npm modules
# todo