#!/bin/bash
set -euxo pipefail

# install prezto
[ ! -d ~/.zprezto ] && git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

# install tmux-powerline
[ ! -d ~/tool/tmux-powerline ] && git clone git://github.com/erikw/tmux-powerline.git ~/tool/tmux-powerline

# setup git-secrets
git secrets --install ~/.git-templates/git-secrets
git config --global init.templatedir "$HOME/.git-templates/git-secrets"