#!/bin/bash
set -euxo pipefail

cd "$(dirname "$0")"

test -t 0 && sudo -v

export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.share

./dotfiles

# If the execution environment is mac, execute the following command.
if [ "$(uname)" == 'Darwin' ]; then

./macos
./brew
brew bundle install
fc-cache -vf
./install-pam

else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi

./other-setup
