#!/bin/bash

cmdname="$(basename "${BASH_SOURCE[0]}")"

if [[ $# -ne 1 ]]; then
  echo "Usage: $cmdname formula" > /dev/stderr
  exit 1
fi

formula=$1

if ! mas list "$formula"; then
  mas install "$formula"
fi